services:
  # x86_64 build (for most Linux distributions)
  prophet-kacou-x86_64:
    build:
      context: .
      dockerfile: Dockerfile.x86_64
      platforms:
        - linux/amd64
    container_name: prophet-kacou-x86_64
    environment:
      - CI=true
      - APPIMAGE_EXTRACT_AND_RUN=1
      - NO_STRIP=1
    volumes:
      - ./artifacts-x86_64:/artifacts
      - node_modules_cache_x86_64:/app/node_modules
      - cargo_cache_x86_64:/home/tauri/.cargo
    working_dir: /app
    user: tauri
    command: >
      sh -c "
        echo 'x86_64 build completed! Copying artifacts...' &&
        echo 'Installing dependencies...' &&
        pnpm install --no-frozen-lockfile &&
        echo 'Building Tauri AppImage...' &&
        pnpm tauri build --bundles appimage &&
        echo 'Copying artifacts...' &&
        mkdir -p /artifacts-x86_64 &&
        cp -r /app/src-tauri/target/release/bundle/* /artifacts/ 2>/dev/null &&
        cp /app/src-tauri/target/release/ProphetKacou /artifacts/ 2>/dev/null &&
        echo 'x86_64 artifacts:' &&
        ls -la /artifacts/
      "

volumes:
  # x86_64 caches
  node_modules_cache_x86_64:
  cargo_cache_x86_64: