name: Prophet Kacou Release Process
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
    inputs:
      application:
        description: "The fully qualified slug of your app on CrabNebula Cloud"
        required: true
        default: "prophet-kacou/prophet-kacou"

env:
  CN_APPLICATION: ${{ vars.CN_APPLICATION }}
  APPLE_ID: ${{ vars.APPLE_ID }}
  APPLE_ID_PASSWORD: ${{ vars.APPLE_ID_PASSWORD }}
  APPLE_EXPORT_CERTIFICATE_PASSWORD: ${{ vars.APPLE_EXPORT_CERTIFICATE_PASSWORD }}
  CN_API_KEY: ${{ vars.CN_API_KEY }}
  RELEASE_NOTE: ./release-notes.txt
  APPLE_CERTIFICATE: ${{ vars.APPLE_CERTIFICATE }}
  KEYCHAIN_PASSWORD: ${{ vars.KEYCHAIN_PASSWORD }}
  TAURI_SIGNING_PRIVATE_KEY: ${{ vars.TAURI_SIGNING_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ vars.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: create draft release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release draft ${{ env.CN_APPLICATION }} --framework tauri --notes-file ${{ env.RELEASE_NOTE }}
          api-key: ${{ env.CN_API_KEY }}

  build:
    needs: draft
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS Universal (combines x86_64 and aarch64)
          - os: macos-latest
            target: universal-apple-darwin
            name: "macOS Universal"
          
          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: "Windows x64"
          - os: windows-latest
            target: i686-pc-windows-msvc
            name: "Windows x86"
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            name: "Windows ARM64"
          
          # Linux builds
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            name: "Linux x64"
          - os: ubuntu-22.04
            target: i686-unknown-linux-gnu
            name: "Linux x86"
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
            name: "Linux ARM64"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
          
      # Install Tauri CLI globally
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli
          
      # Linux dependencies for all Linux targets
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          sudo apt-get install -y gcc-multilib
          
      # Install cross-compilation toolchains for Linux
      - name: Install Linux cross-compilation dependencies
        if: matrix.os == 'ubuntu-22.04' && matrix.target != 'x86_64-unknown-linux-gnu'
        run: |
          case "${{ matrix.target }}" in
            "i686-unknown-linux-gnu")
              sudo apt-get install -y gcc-i686-linux-gnu
              echo "CC_i686_unknown_linux_gnu=i686-linux-gnu-gcc" >> $GITHUB_ENV
              echo "CXX_i686_unknown_linux_gnu=i686-linux-gnu-g++" >> $GITHUB_ENV
              ;;
            "aarch64-unknown-linux-gnu")
              sudo apt-get install -y gcc-aarch64-linux-gnu
              echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
              ;;
          esac
          
      # Add Rust targets - Handle universal-apple-darwin specially
      - name: Add Rust target
        run: |
          if [ "${{ matrix.target }}" = "universal-apple-darwin" ]; then
            echo "Setting up universal binary targets for macOS..."
            rustup target add x86_64-apple-darwin
            rustup target add aarch64-apple-darwin
            echo "Targets installed for universal binary"
          else
            echo "Installing target: ${{ matrix.target }}"
            rustup target add ${{ matrix.target }}
          fi
        
      # Install pnpm dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      # Build for macOS Universal - Let Tauri handle the universal binary
      - name: Build macOS Universal
        if: matrix.os == 'macos-latest'
        run: |
          echo "Building universal macOS binary..."
          # Option 1: Use pnpm (current approach)
          pnpm tauri build --target universal-apple-darwin --config ./src-tauri/tauri.onlineappstore.conf.json
          
          # Option 2: Alternative using global CLI (uncomment if pnpm fails)
          # tauri build --target universal-apple-darwin --config ./src-tauri/tauri.onlineappstore.conf.json
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ env.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          
      # Build for Windows
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: pnpm tauri build --target ${{ matrix.target }}
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ env.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          
      # Build for Linux
      - name: Build Linux
        if: matrix.os == 'ubuntu-22.04'
        run: pnpm tauri build --target ${{ matrix.target }}
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ env.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          
      # Upload assets
      - name: Upload assets
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release upload ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ env.CN_API_KEY }}
          path: ./src-tauri

  publish:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release publish ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ env.CN_API_KEY }}